"""Markdown assembly for the per-state sentiment reports.

Every figure is taken verbatim from StateAggregates; the narrative is the only
LLM-authored text and always passes through sanitize_narrative before it is
embedded (heading demotion, think-tag stripping, HTML escaping, length cap).
"""
from __future__ import annotations

import re

from warn_v2.reports.aggregate import DeltaRow, StateAggregates

MAX_NARRATIVE_CHARS = 4000

_THINK_RE = re.compile(r"<think>.*?</think>", re.DOTALL | re.IGNORECASE)
_HEADING_RE = re.compile(r"^\s{0,3}#{1,6}\s*", re.MULTILINE)


def sanitize_narrative(text: str) -> str:
    """Neutralize LLM output for safe embedding: strip leaked chain-of-thought,
    demote headings (they would break the report's structure), escape HTML,
    collapse blank runs, cap length."""
    text = _THINK_RE.sub("", text)
    text = _HEADING_RE.sub("", text)
    text = text.replace("<", "&lt;").replace(">", "&gt;")
    text = re.sub(r"\n{3,}", "\n\n", text).strip()
    if len(text) > MAX_NARRATIVE_CHARS:
        text = text[:MAX_NARRATIVE_CHARS].rstrip() + "…"
    return text


def _signed(n: int) -> str:
    return f"{n:+d}" if n else "0"


def _escape_cell(text: str) -> str:
    """Neutralize scraped strings (county names) for markdown table cells:
    a literal | breaks the row, and <> could smuggle HTML past the
    narrative-only sanitization."""
    return text.replace("|", "\\|").replace("<", "&lt;").replace(">", "&gt;")


def _pct_cell(row: DeltaRow) -> str:
    if row.pct_change is not None:
        return f"{row.pct_change:+.0f}%"
    return "new" if row.cur_layoffs else "—"


def _delta_table(rows: list[DeltaRow], label: str, limit: int = 15) -> str:
    if not rows:
        return "_No notices in either window._"
    lines = [
        f"| {label} | Notices (cur) | Layoffs (cur) | Layoffs (prior) | Δ | Δ% |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    for r in rows[:limit]:
        lines.append(
            f"| {_escape_cell(r.name)} | {r.cur_notices} | {r.cur_layoffs} | {r.prior_layoffs} "
            f"| {_signed(r.delta_layoffs)} | {_pct_cell(r)} |"
        )
    return "\n".join(lines)


def _monthly_table(monthly: list[tuple[str, int, int]]) -> str:
    if not monthly:
        return "_No notices in the last 12 months._"
    lines = ["| Month | Notices | Workers affected |", "|---|---:|---:|"]
    lines += [f"| {m} | {n} | {lt} |" for m, n, lt in monthly]
    return "\n".join(lines)


def _closure_line(split: dict[str, int]) -> str:
    if not split:
        return ""
    order = ["Layoff", "Closure", "Unspecified"]
    parts = [f"{split[k]} {k}" for k in order if k in split]
    parts += [f"{v} {k}" for k, v in sorted(split.items()) if k not in order]
    return f"\nCurrent-window notice mix: {' · '.join(parts)}.\n"


def _sentiment_section(
    agg: StateAggregates, narrative: str | None, narrative_status: str
) -> str:
    if narrative_status == "ok" and narrative is not None:
        return sanitize_narrative(narrative)
    if narrative_status == "insufficient_data":
        days = (agg.cur_end - agg.prior_start).days + 1
        return (
            f"Insufficient recent WARN activity in {agg.state_name} to support a "
            f"trend narrative ({agg.cur_notices + agg.prior_notices} notices in "
            f"the last {days} days)."
        )
    if narrative_status == "llm_unavailable":
        return (
            "Narrative unavailable this week (LLM service unreachable). "
            "The deterministic figures below are current."
        )
    # "skipped" (--skip-llm)
    return "Narrative generation was skipped. The deterministic figures below are current."


def render_report(
    agg: StateAggregates,
    narrative: str | None,
    *,
    narrative_status: str = "ok",
    model: str | None = None,
) -> str:
    """Assemble the full report. narrative_status is one of:
    ok | insufficient_data | llm_unavailable | skipped."""
    days = (agg.cur_end - agg.cur_start).days + 1
    narrative_credit = (
        f" Narrative generated by {model}; any numbers in the prose are drawn "
        f"from the tables above." if narrative_status == "ok" and model else ""
    )
    notices_row = (
        f"| Notices | {agg.cur_notices} | {agg.prior_notices} "
        f"| {_signed(agg.cur_notices - agg.prior_notices)} "
        f"| {agg.yoy_cur_notices} | {agg.yoy_prior_notices} |"
    )
    layoffs_row = (
        f"| Workers affected | {agg.cur_layoffs} | {agg.prior_layoffs} "
        f"| {_signed(agg.cur_layoffs - agg.prior_layoffs)} "
        f"| {agg.yoy_cur_layoffs} | {agg.yoy_prior_layoffs} |"
    )
    return f"""# {agg.state_name} ({agg.state}) — WARN Layoff Trends

_Generated {agg.as_of.isoformat()} · Current window {agg.cur_start.isoformat()} → \
{agg.cur_end.isoformat()} vs prior {agg.prior_start.isoformat()} → {agg.prior_end.isoformat()}_

## Summary

| Metric | Current {days}d | Prior {days}d | Δ | Trailing 12mo | Prior 12mo |
|---|---:|---:|---:|---:|---:|
{notices_row}
{layoffs_row}
{_closure_line(agg.closure_split)}
## Sentiment

{_sentiment_section(agg, narrative, narrative_status)}

## Where layoffs are shifting — by county

{_delta_table(agg.counties, "County")}

## Industry pressure — NAICS sectors

{_delta_table(agg.sectors, "Sector")}

_NAICS coverage: {agg.naics_coverage_pct:.0f}% of current-window notices have an enriched company._

## Monthly trend (last 12 months)

{_monthly_table(agg.monthly)}

---

_Deterministic figures computed from non-superseded WARN notices bucketed by \
notice date; notices without a reported worker count contribute 0 to the \
workers-affected sums.{narrative_credit}_
"""
