"""Tests for `warn-v2 sentiment-report`, focused on file output and the
exit-code policy (partial narrative failures degrade; total failure exits 1)."""
from __future__ import annotations

from datetime import date, timedelta

import pytest
from click.testing import CliRunner

from warn_v2 import cli
from warn_v2.db.models import Notice
from warn_v2.reports import ollama as ollama_mod
from warn_v2.reports.ollama import OllamaUnavailable


class FakeNarrativeClient:
    """Scripted stand-in for OllamaClient."""

    model = "fake-model"

    def __init__(self, *, fail: bool = False):
        self.fail = fail
        self.calls = 0

    def narrate(self, *, system: str, prompt: str) -> str:
        self.calls += 1
        if self.fail:
            raise OllamaUnavailable("down")
        return "Layoff activity increased."


def _seed_state(db, state: str, n: int = 6) -> None:
    """Enough recent notices to clear the MIN_NOTICES narrative threshold."""
    recent = date.today() - timedelta(days=10)
    for i in range(n):
        db.add(
            Notice(
                notice_id=f"cli_{state}_{i}",
                state=state,
                employer=f"Employer {i}",
                notice_date=recent,
                layoff_count=10,
            )
        )
    db.commit()


@pytest.fixture
def fake_client(monkeypatch: pytest.MonkeyPatch) -> FakeNarrativeClient:
    fake = FakeNarrativeClient()
    monkeypatch.setattr(ollama_mod, "build_ollama_client", lambda: fake)
    return fake


def test_single_state_with_narrative(db, fake_client, tmp_path):
    _seed_state(db, "CA")
    result = CliRunner().invoke(
        cli.main, ["sentiment-report", "--state", "CA", "--reports-dir", str(tmp_path)]
    )
    assert result.exit_code == 0, result.output
    assert fake_client.calls == 1
    content = (tmp_path / "CA.md").read_text(encoding="utf-8")
    assert "Layoff activity increased." in content
    assert "Narrative generated by fake-model" in content
    assert "narrative_ok=1" in result.output


def test_skip_llm_never_touches_client(db, fake_client, tmp_path):
    _seed_state(db, "CA")
    result = CliRunner().invoke(
        cli.main,
        ["sentiment-report", "--state", "CA", "--reports-dir", str(tmp_path), "--skip-llm"],
    )
    assert result.exit_code == 0, result.output
    assert fake_client.calls == 0
    assert "Narrative generation was skipped" in (tmp_path / "CA.md").read_text(encoding="utf-8")


def test_dry_run_writes_nothing(db, fake_client, tmp_path):
    _seed_state(db, "CA")
    result = CliRunner().invoke(
        cli.main,
        ["sentiment-report", "--state", "CA", "--reports-dir", str(tmp_path), "--dry-run"],
    )
    assert result.exit_code == 0, result.output
    assert list(tmp_path.iterdir()) == []
    assert "(dry run — nothing written)" in result.output


def test_all_narratives_failed_exits_1(db, fake_client, tmp_path):
    fake_client.fail = True
    _seed_state(db, "CA")
    result = CliRunner().invoke(
        cli.main, ["sentiment-report", "--state", "CA", "--reports-dir", str(tmp_path)]
    )
    assert result.exit_code == 1
    # The degraded report is still written before the exit code flips.
    assert "Narrative unavailable this week" in (tmp_path / "CA.md").read_text(encoding="utf-8")
    assert "narrative_failed=1" in result.output


def test_insufficient_state_skips_llm_and_exits_0(db, fake_client, tmp_path):
    # No notices at all: report written, LLM never called, exit 0.
    result = CliRunner().invoke(
        cli.main, ["sentiment-report", "--state", "WY", "--reports-dir", str(tmp_path)]
    )
    assert result.exit_code == 0, result.output
    assert fake_client.calls == 0
    assert "Insufficient recent WARN activity" in (tmp_path / "WY.md").read_text(encoding="utf-8")


def test_unknown_state_rejected(db, fake_client, tmp_path):
    result = CliRunner().invoke(
        cli.main, ["sentiment-report", "--state", "ZZ", "--reports-dir", str(tmp_path)]
    )
    assert result.exit_code == 1
    assert "unknown state" in result.output
