{{- if .Values.reportStorage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "warn-v2.fullname" . }}-reports
  labels:
    {{- include "warn-v2.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteMany]
  storageClassName: {{ .Values.reportStorage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.reportStorage.size }}
{{- end }}
