"""add notice_occupations table

Revision ID: b3e3a81da979
Revises: ee109f1b0516
Create Date: 2026-07-09 23:55:54.819558

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b3e3a81da979'
down_revision: str | None = 'ee109f1b0516'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notice_occupations',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
              autoincrement=True, nullable=False),
    sa.Column('notice_id', sa.String(length=64), nullable=False),
    sa.Column('job_title', sa.Text(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True),
              server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notice_id'], ['notices.notice_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notice_id', 'job_title', name='uq_notice_occupations_notice_title')
    )
    op.create_index(op.f('ix_notice_occupations_notice_id'), 'notice_occupations',
                    ['notice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notice_occupations_notice_id'), table_name='notice_occupations')
    op.drop_table('notice_occupations')
    # ### end Alembic commands ###
