"""add api_keys table

Revision ID: c6350a95fde9
Revises: c7f606bfd7bd
Create Date: 2026-07-06 15:30:36.501852

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c6350a95fde9'
down_revision: str | None = 'c7f606bfd7bd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
              autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('key_sha256', sa.String(length=64), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    # autogen against SQLite rendered '(CURRENT_TIMESTAMP)'; use the portable form
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(),
              nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_sha256'), 'api_keys', ['key_sha256'], unique=True)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_sha256'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
