"""add auth tokens and user verification columns

Revision ID: 40821b8384e6
Revises: 2534434fc870
Create Date: 2026-07-06 15:51:03.154034

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '40821b8384e6'
down_revision: str | None = '2534434fc870'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_tokens',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
              autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('token_sha256', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    # autogen against SQLite rendered '(CURRENT_TIMESTAMP)'; use the portable form
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(),
              nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_tokens_token_sha256'), 'auth_tokens', ['token_sha256'],
                    unique=True)
    op.create_index(op.f('ix_auth_tokens_user_id'), 'auth_tokens', ['user_id'], unique=False)
    op.add_column('users',
                  sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_stripe_customer_id'), 'users', ['stripe_customer_id'],
                    unique=True)
    # Pre-signup rows are all admin-provisioned — treat them as verified so the
    # new email-verification gate (API key creation) doesn't lock them out.
    op.execute("UPDATE users SET email_verified_at = CURRENT_TIMESTAMP "
               "WHERE email_verified_at IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_stripe_customer_id'), table_name='users')
    op.drop_column('users', 'stripe_customer_id')
    op.drop_column('users', 'email_verified_at')
    op.drop_index(op.f('ix_auth_tokens_user_id'), table_name='auth_tokens')
    op.drop_index(op.f('ix_auth_tokens_token_sha256'), table_name='auth_tokens')
    op.drop_table('auth_tokens')
    # ### end Alembic commands ###
