"""add index on notices.effective_date

Revision ID: ee109f1b0516
Revises: 40821b8384e6
Create Date: 2026-07-09 23:18:33.835056

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ee109f1b0516'
down_revision: str | None = '40821b8384e6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_notices_effective_date'), 'notices', ['effective_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notices_effective_date'), table_name='notices')
    # ### end Alembic commands ###
