"""add source_cache

Revision ID: c7f606bfd7bd
Revises: r9b0c1d2e3f4
Create Date: 2026-07-02 01:37:31.728262

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c7f606bfd7bd'
down_revision: str | None = 'r9b0c1d2e3f4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_cache',
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('etag', sa.String(length=256), nullable=True),
    sa.Column('last_modified', sa.String(length=128), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('url')
    )
    op.create_index(op.f('ix_source_cache_state'), 'source_cache', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_cache_state'), table_name='source_cache')
    op.drop_table('source_cache')
    # ### end Alembic commands ###
