"""add bls_series

Revision ID: 522e7cb32eb7
Revises: 551b7466239a
Create Date: 2026-09-28 10:19:22.853671

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '522e7cb32eb7'
down_revision: str | None = '551b7466239a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bls_series',
    sa.Column('series_id', sa.String(length=32), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('series_id', 'period')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bls_series')
    # ### end Alembic commands ###
