"""Fetch US state outline paths and generate the frontend SVG map module.

Parses Wikimedia Commons "Blank US Map (states only).svg" (CC0 1.0 public
domain, by Heitordp) -- an Albers-style layout with Alaska/Hawaii insets and
one <path> per jurisdiction (50 states + DC), keyed by lowercase postal code:
    https://commons.wikimedia.org/wiki/File:Blank_US_Map_(states_only).svg

Output: frontend/src/lib/usStatePaths.ts

Stdlib only (urllib, not httpx) so it also runs outside the uv environment.

Run with:
    python -m warn_v2.scripts.fetch_us_state_paths [local_svg_path]
"""

from __future__ import annotations

import logging
import re
import sys
import urllib.request
from pathlib import Path

log = logging.getLogger(__name__)

_SOURCE_URL = (
    "https://upload.wikimedia.org/wikipedia/commons/1/1a/Blank_US_Map_%28states_only%29.svg"
)
_SOURCE_PAGE = "https://commons.wikimedia.org/wiki/File:Blank_US_Map_(states_only).svg"
_OUT_PATH = Path(__file__).parent.parent.parent / "frontend" / "src" / "lib" / "usStatePaths.ts"

# The source SVG has width=959 height=593 but no viewBox attribute.
_VIEWBOX = "0 0 959 593"
# Anchor of the (tiny) real DC geometry, taken from the source file's DC
# callout circle -- used by the frontend for its own callout leader line.
_DC_ANCHOR = (801.6, 252.1)

# Must mirror US_STATES in frontend/src/lib/format.ts (50 states + DC).
_EXPECTED_CODES = {
    "AK",
    "AL",
    "AR",
    "AZ",
    "CA",
    "CO",
    "CT",
    "DC",
    "DE",
    "FL",
    "GA",
    "HI",
    "IA",
    "ID",
    "IL",
    "IN",
    "KS",
    "KY",
    "LA",
    "MA",
    "MD",
    "ME",
    "MI",
    "MN",
    "MO",
    "MS",
    "MT",
    "NC",
    "ND",
    "NE",
    "NH",
    "NJ",
    "NM",
    "NV",
    "NY",
    "OH",
    "OK",
    "OR",
    "PA",
    "RI",
    "SC",
    "SD",
    "TN",
    "TX",
    "UT",
    "VA",
    "VT",
    "WA",
    "WI",
    "WV",
    "WY",
}


def fetch_svg(local_path: str | None) -> str:
    if local_path:
        log.info("Reading local SVG %s", local_path)
        return Path(local_path).read_text(encoding="utf-8")
    log.info("Fetching %s", _SOURCE_URL)
    req = urllib.request.Request(
        _SOURCE_URL,
        headers={"User-Agent": "warn-v2/0.1 (research; raphael@wielandtech.com)"},
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read().decode("utf-8")


def extract_paths(svg_text: str) -> dict[str, str]:
    """Extract {UPPERCASE code: path d} for the 51 jurisdiction paths."""
    result: dict[str, str] = {}
    # One <path class="xx" d="..."> per jurisdiction; the DC callout circle
    # is a <circle>, so this matches exactly the 51 state paths.
    for code, d in re.findall(r'<path class="([a-z]{2})" d="([^"]+)"', svg_text):
        d = re.sub(r"\s+", " ", d).strip()
        if re.search(r'["\\`]', d):
            raise RuntimeError(f"Path data for {code} contains characters needing TS escaping")
        result[code.upper()] = d

    if set(result) != _EXPECTED_CODES:
        missing = _EXPECTED_CODES - set(result)
        extra = set(result) - _EXPECTED_CODES
        raise RuntimeError(
            f"State code mismatch -- missing: {sorted(missing)}, extra: {sorted(extra)}"
            " -- source file format may have changed"
        )
    return result


def render_module(paths: dict[str, str]) -> str:
    lines = [
        "// GENERATED by warn_v2/scripts/fetch_us_state_paths.py -- do not edit by hand.",
        '// Source: Wikimedia Commons "Blank US Map (states only).svg", CC0 1.0 public domain.',
        f"// {_SOURCE_PAGE}",
        "",
        f'export const US_MAP_VIEWBOX = "{_VIEWBOX}";',
        "",
        "/** Anchor of the real (tiny) DC geometry, for the callout leader line. */",
        f"export const DC_ANCHOR = {{ x: {_DC_ANCHOR[0]}, y: {_DC_ANCHOR[1]} }};",
        "",
        "export const US_STATE_PATHS: Record<string, string> = {",
    ]
    for code in sorted(paths):
        lines.append(f'  {code}: "{paths[code]}",')
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s  %(message)s")
    svg_text = fetch_svg(sys.argv[1] if len(sys.argv) > 1 else None)
    paths = extract_paths(svg_text)
    module = render_module(paths)
    _OUT_PATH.write_text(module, encoding="utf-8", newline="\n")
    log.info("Wrote %d state paths to %s (%d bytes)", len(paths), _OUT_PATH, len(module))


if __name__ == "__main__":
    main()
